import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";

export const metadata: Metadata = {
  title: "Duoleet",
  description: "Generated by create next app",
  // Correct path to the favicon image
  icons: {
    icon: "/images/duoleet-eagle.png", // Link to the image in the public folder
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add your favicon link */}
        <link rel="icon" href="/images/duoleet-eagle.png" />
        {/* Optionally add other icon sizes */}
        {/* <link rel="icon" href="/favicon.png" type="image/png" /> */}
      </head>
      <AuthProvider>
        <body>{children}</body>
      </AuthProvider>
    </html>
  );
}
